### ISSUE TITLE
need day's database.db and image_pairs_to match.txt

### ISSUE THREAD

**Issue by fantuslk** [tsattler/visuallocalizationbenchmark#24]
Hi,@tsattler,without the two files,i can't  obtain the submit txt of day. Please provide it.

**Comment by tsattler** [comment]
I assume that this is for the Aachen dataset? The daytime images are included in the database that is released with the dataset.

If you are planning to evaluate a localization algorithm and not just local features, do not use the image pairs provided by the local feature challenge. They are meant to make it easy to evaluate local features without having to worry about retrieving relevant database images. But they also provide knowledge that is typically not available for a full localization system. In order to find image pairs, use image retrieval to identify pairs of images that should be matched.

**Comment by fantuslk** [comment]
Thank you very much for your reply.I am just testing mylocalization algorithm.Which image retrieval software can help get the match txt?

**Comment by tsattler** [comment]
Please have a look at the literature. E.g., you can have a look at the top-performing methods on the benchmark and see which image retrieval algorithms are used.

**Comment by reacher-l** [comment]
> Hi,@tsattler,without the two files,i can't obtain the submit txt of day. Please provide it.

Hello, Have you found the image_pairs_to match-.txt of the day data set ?

**Comment by tsattler** [comment]
We only provide pairs to match for the nighttime queries and for the database images. We do not have such a file for the daytime queries. You can create them yourself using image retrieval.
