### ISSUE TITLE
need more results

### ISSUE THREAD

**Issue by fantuslk** [tsattler/visuallocalizationbenchmark#25]
hi，@tsattler,,in the website,only get the result of (0.5m,2),(1m,5),(5m,10),how can I get the result of the features and (10m,25) in the d2-net paper?
such as:
Correctly localized queries (%)
Method # Features 0.5m, 2◦ 1.0m, 5◦ 5.0m, 10◦ 10m, 25◦
Upright RootSIFT [29] 11.3K 36.7 54.1 72.5 81.6...

**Comment by tsattler** [comment]
We are currently only providing results for (0.5m,2), (1m,5), and (5m,10). We are currently not planning to include (10m,25) as we want to measure accurate localization performance.

**Comment by fantuslk** [comment]
Thank you for your answer,and how can I get the result of #Features ?

**Comment by tsattler** [comment]
You should be able to measure the number of features your method extracts and can then compare against what has been reported in the literature.

**Comment by fantuslk** [comment]
Ok,I know.

**Comment by Enderych** [comment]
Hi @tsattler, I have a related question: if I have an absolute localization method with better performance of rotation rather than translation, for example, average rotation error < 2° while average translation error ≈ 1 m, how can I see the difference in your test report?
I mean, if next time I changed some parameters, then improved the translation performance but decreased the rotation performance, can I see this change from the benchmark report?

**Comment by tsattler** [comment]
We report the percentage of images localized within certain error bounds on rotation **and** translation. If your changes lead to a large enough improvement, you should thus see this on the benchmark results.

Notice that rotation and translation errors are not independent of each other, i.e., a rotation can sometimes compensate for a translation and vice versa. So it does not make much sense to look at them individually.

**Comment by Enderych** [comment]
That's what I concerned, since the percentage for (0.5m,2),(1m,5),(5m,10) (night) & (0.25m,2),(0.5m,5),(5m,10) (day) seems much stricter to translation. Maybe method A has very similar performance on translation but better performance on rotation, compare with method B, while A and B might get very close percentage in the benchmark report, is that possible? Can we also get the mean or median error of translation and rotation, separately?

**Comment by tsattler** [comment]
Using a stricter criterion is the point of the evaluation we are doing. 

If you have a median position error of 10cm and 5deg, that does not give you any guarantee that there is any image with a position error <= 10cm **and** an orientation error of 5deg. Here is an extreme example: Algorithm A has a median error of 10cm, 5deg, Algorithm B has 12cm, 6deg. For each pose of Algorithm A, you either have a position error > 10cm or an orientation error > 5deg. 50% of all poses generated by Algorithm B have a position error <= 12cm and an orientation error <= 6deg. Based on the median errors, Algorithm A seems better, but I would argue that Algorithm B is actually better.
I don't think it makes sense to look at the errors in isolation and we are not planning to compute median and mean errors.

**Comment by Enderych** [comment]
I see what you mean, that rotation and translation should be considered together, performance increasing on only one side does not mean better localization. 
But my suggestion is that when two methods have similar performance on this percentage standard, then compare their mean or median error of translation and rotation will be reasonable.  While maybe this suggestion is not practical now since many methods have already been tested.
Thanks again, I will try to do experiments with the current standard.
