### ISSUE TITLE
About the training set of Aachen-day-night

### ISSUE THREAD

**Issue by shamangary** [tsattler/visuallocalizationbenchmark#4]
Hello. I was there at the CVPR workshop and I have some questions about the evaluation so I want to ask the official benchmark manager.

I was reading the workshop paper "R2D2: Repeatable and Reliable Detector and Descriptor". 

Is it fair to train on Aachen and test on Aachen also? Because it seems like the results of R2D2 (Tab.3 and Tab.4 from https://arxiv.org/pdf/1906.06195.pdf) use Aachen to train and test. Even with style transfer, I think it would be fairer if they use other dataset and adopt style transfer, but definitely not Aachen.

It seems like only the results on Tab.4 with "W" option (W=web images + homographies) is suitable for testing on Aachen and it is much lower.

**Comment by tsattler** [comment]
@shamangary I think it is fine to use the daytime images of Aachen for training (or style-transferred versions of them). Localization is a scene-specific problem and most localization methods will use the daytime images for training.

There is a point to be made of creating local features that generalize well. But there is also value in having features tailored specifically to a scene.

**Comment by kienduynguyen** [comment]
Hi,

I have some questions about your comment! If you accept the day images of Aachen for training, so that mean the evaluation is only for the testing of robustness of descriptor over the change of illumination and light. And, you say localization is a scene-specific problem, does that mean we need to train different models for different scenes (overfit every scene)? Thank you!

**Comment by tsattler** [comment]
The goal of the whole benchmark is to evaluate the robustness of visual localization algorithms (or their components such as local features) under changing conditions. As such, we provide reference images taken under the same condition (day for Aachen), together with their camera poses. For testing, we provide images taken under different conditions (night for Aachen) without known poses. The goal is to be able to estimate the position and orientation from which these test images were taken wrt. to the reference images for as many test images as possible and as accurately as possible.

Visual localization is the problem of estimating the position and orientation from which an image was taken wrt. to a given scene. Learning-based approaches typically use the reference images to learn a mapping from images to camera poses or from image patches to 3D points in the scene. This is a scene-specific problem. For example, having reference images for Aachen with known poses will not help you localize images in Paris. So you need to train per scene. However, this does not mean that you necessarily overfit to each scene.

Since visual localization algorithms typically build a scene-specific representation, and since we are evaluating local features in the context of visual localization, I don't see why it would not be fair game to train on the day images of Aachen.
