### ISSUE TITLE
false extrinsics in aachen_cvpr2018_db.nvm

### ISSUE THREAD

**Issue by Matstah** [tsattler/visuallocalizationbenchmark#49]
Hi

Image db/1228.jpg seems to have false extrinsics inside the aachen_cvpr2018_db.nvm.

Currently, the line (name, _, qw, qx, qy, qz, cx, cy, cz, _, _) in .nvm file sais:

db/1228.jpg 1603.26000000 -0.026940300000 -0.225850000000 0.104937000000 0.968119000000 782.070000000000 -8.563600000000 -276.338000000000 -0.255289000000 0

![img 1228 with false extrinsics](https://user-images.githubusercontent.com/48456608/129482259-4217465f-c25a-4b9a-9794-38510b39c072.png)

![1228](https://user-images.githubusercontent.com/48456608/129482417-3bbedd41-c438-4652-9ee9-137d60c3b103.jpg)

**Comment by tsattler** [comment]
Yes, this can happen for some database images as an automated algorithm (COLMAP) is used to build the reference model and since this type of behavior can happen with Structure-from-Motion algorithms. 

Note that there are no query images in this region of the model and you can safely remove this image from the model if it causes problems for your approach.
