### ISSUE TITLE
The test results on the Aachen Day-night dataset are only Night, and the daytime results are 0

### ISSUE THREAD

**Issue by reacher-l** [tsattler/visuallocalizationbenchmark#56]
Why the test results on the Aachen Day-night dataset are only Night, and the daytime results are 0?

**Comment by tsattler** [comment]
Hard to tell without any details. 
I assume you are using the pipeline and data provided in this repository? If this is the case, the reason why you get all zeroes for the daytime images is that they are not processed. Only nighttime images are currently processed. The reason is that we provide here the data to run experiments for a challenge from previous CVPR and ECCV workshops, which focused on the nighttime images.
