### ISSUE TITLE
The scale and orientation of the descriptors in CMU dataset

### ISSUE THREAD

**Issue by zhangpengju0316** [tsattler/visuallocalizationbenchmark#8]
Hi, I found the scale and orientation of the descriptors of the CMU database images are 1 and 0, does the orientation of the descriptors of the CMU database images provided by the CMU dataset are the orientation reported by the keypoint detector ? Does the features of the CMU database images are upright features just like RobotCar-Seasons ?

**Comment by tsattler** [comment]
@zhangpengju0316 Can you be a bit more specific about which version of the CMU dataset you are using (original vs. extended)? Where do you read the descriptors from?

**Comment by zhangpengju0316** [comment]
@tsattler  I I use original CMU dataset and read from the path 

> CMU-Seasons/sift_descriptors/slice2/...

the README_CMU_Seasons.md in CMU dataset says that:

> ### SIFT Descriptors
The SIFT descriptors are provided in the  `sift_descriptors.zip` file. They are stored in the binary file format used by [VisualSfM](http://ccwu.me/vsfm/index.html) as described [here](http://ccwu.me/vsfm/doc.html#customize). ...

**Comment by tsattler** [comment]
Thanks for the clarification. The SIFT descriptors have been extracted in an upright position, which is the reason why all orientations are set to 0. The reason why the scales are set to 1 is that we did not export them. Does this answer your question?

**Comment by zhangpengju0316** [comment]
Yes, I see, thank you very much. 
And I want ask that, can you provide scale information, because if there is no scale information, I can't extract other descriptors,like brisk, needed by my localization algorithm. So I can't evaluate my localization algorithm in CMU dataset. Or is there any other way or method to get scale information of the keypoints in CMU database images?

**Comment by tsattler** [comment]
@zhangpengju0316 I don't think we still have the original features around. You could extract features from scratch and then only triangulate the scene using the given camera poses, which can be done very efficiently. This would give you a new 3D model with features with known scales and orientations.
The extended version of the CMU dataset provides the original COLMAP databases, which contain the full feature geometry. You could use the extended version of the dataset instead of the original one.

**Comment by zhangpengju0316** [comment]
Wow, Great! I will have a try. Thank you again !
